[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "poetry"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd mysite && python manage.py runserver 0.0.0.0:8000"
